import React, { useState, useEffect } from 'react';
import { db } from '../firebase';
import { 
  collection, 
  onSnapshot, 
  doc, 
  updateDoc, 
  serverTimestamp 
} from 'firebase/firestore';
import { 
  Sparkles, 
  User, 
  Clock, 
  CheckCircle, 
  HelpCircle, 
  AlertCircle,
  Gem,
  Hammer,
  Search,
  Sliders,
  FileText
} from 'lucide-react';
const translations = {
  en: {
    title: "AI Custom Designs",
    subtitle: "Review and manage unique jewelry custom models generated by clients using generative prompts",
    searchPlaceholder: "Search custom designs by prompt, materials, or client...",
    statusLabel: "Status:",
    filterAll: "All Designs",
    filterCreated: "Created",
    filterReview: "Under Review",
    filterApproved: "Approved",
    filterRejected: "Unfeasible",
    loadingText: "Fetching generative creations board...",
    noDesigns: "No customer custom designs found matching filters.",
    
    // Status Badges
    badgeCreated: "Design Created",
    badgeReview: "Reviewing Feasibility",
    badgeApproved: "Approved for Casting",
    badgeRejected: "Unfeasible",
    
    // Card labels
    clientPrompt: "Client Prompt",
    selectedComposition: "Selected Composition",
    
    // Card buttons
    btnReview: "Feasibility Review",
    btnApprove: "Approve Casting",
    btnReject: "Reject",
    btnReset: "Reset Workflow",
    
    // Alerts
    alertSaveErr: "Failed to update workflow: "
  },
  vi: {
    title: "Thiết Kế AI Khách Hàng",
    subtitle: "Xem xét và quản lý các mẫu trang sức tùy chỉnh độc đáo được tạo ra bởi khách hàng bằng cách sử dụng các câu lệnh mô tả (prompts)",
    searchPlaceholder: "Tìm kiếm thiết kế tùy chỉnh theo prompt, chất liệu hoặc khách hàng...",
    statusLabel: "Trạng thái:",
    filterAll: "Tất cả thiết kế",
    filterCreated: "Đã tạo",
    filterReview: "Đang đánh giá",
    filterApproved: "Đã phê duyệt",
    filterRejected: "Không khả thi",
    loadingText: "Đang tải danh sách thiết kế sáng tạo AI...",
    noDesigns: "Không tìm thấy thiết kế tùy chỉnh nào của khách hàng phù hợp với bộ lọc.",
    
    // Status Badges
    badgeCreated: "Đã Tạo Thiết Kế",
    badgeReview: "Đang Đánh Giá Khả Thi",
    badgeApproved: "Phê Duyệt Đúc Mẫu",
    badgeRejected: "Không Khách Hiệu",
    
    // Card labels
    clientPrompt: "Prompt của Khách Hàng",
    selectedComposition: "Chất Liệu Đã Chọn",
    
    // Card buttons
    btnReview: "Đánh Giá Khả Thi",
    btnApprove: "Duyệt Đúc Mẫu",
    btnReject: "Từ Chối",
    btnReset: "Đặt Lại Tiến Trình",
    
    // Alerts
    alertSaveErr: "Cập nhật tiến trình thất bại: "
  }
};

export default function AiCustomDesigns({ locale = 'en' }) {
  const t = translations[locale] || translations.en;
  const [designs, setDesigns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [processingId, setProcessingId] = useState(null);

  // --- Premium Luxury Fallback Dataset (Strong Null-Safety Assurance) ---
  const mockDesigns = [
    {
      id: 'mock-1',
      imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop',
      prompt: 'Art Deco style ring with a large center royal blue sapphire, surrounding tiny baguette diamonds, platinum band, highly intricate details',
      material: 'Platinum 950, 3.5ct Royal Blue Sapphire & VVS Baguette Diamonds',
      status: 'Created',
      customerEmail: 'alex.vance@gmail.com',
      createdAt: { toDate: () => new Date(Date.now() - 3600000 * 4) } // 4 hrs ago
    },
    {
      id: 'mock-2',
      imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop',
      prompt: 'Minimalist necklace with a dainty pear-shaped emerald pendant suspended from an 18k yellow gold thin cable chain, elegant luxury',
      material: '18K Yellow Gold, 1.2ct Pear-Shaped Columbian Emerald',
      status: 'Created',
      customerEmail: 'sarah.m@luxury-lifestyle.org',
      createdAt: { toDate: () => new Date(Date.now() - 3600000 * 24) } // 1 day ago
    },
    {
      id: 'mock-3',
      imageUrl: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=600&auto=format&fit=crop',
      prompt: 'Modern geometric earrings, rose gold hexagons with micro-pave pink diamonds lining the inner rims, subtle glow',
      material: '18K Rose Gold, Micro-Pave Pink Diamonds',
      status: 'Manufacturability Review',
      customerEmail: 'eleanor.p@couture.fr',
      createdAt: { toDate: () => new Date(Date.now() - 3600000 * 48) } // 2 days ago
    }
  ];

  useEffect(() => {
    let unsubscribe = null;
    try {
      unsubscribe = onSnapshot(collection(db, 'ai_custom_designs'), (snapshot) => {
        if (!snapshot.empty) {
          const list = snapshot.docs.map(docSnapshot => {
            const data = docSnapshot.data();
            // --- Robust Null-Safety Guardrails ---
            return {
              id: docSnapshot.id,
              imageUrl: data.imageUrl || data.image || '',
              prompt: data.prompt || 'No prompt provided',
              material: data.material || 'Standard Metal & Diamond Blend',
              status: data.status || 'Created',
              customerEmail: data.customerEmail || data.userEmail || 'Anonymous Client',
              createdAt: data.createdAt || null
            };
          });
          setDesigns(list);
        } else {
          // If collection is empty, load our custom premium fallback dataset
          setDesigns(mockDesigns);
        }
        setLoading(false);
      }, (error) => {
        console.warn('Firestore active subscription failed; adopting fallback dataset securely.', error);
        setDesigns(mockDesigns);
        setLoading(false);
      });
    } catch (err) {
      console.error('Firestore init failed; loading mock context securely', err);
      setDesigns(mockDesigns);
      setLoading(false);
    }

    return () => {
      if (unsubscribe) unsubscribe();
    };
  }, []);

  const updateDesignStatus = async (id, targetStatus) => {
    setProcessingId(id);
    try {
      if (id.startsWith('mock-')) {
        // Update local mock state seamlessly for premium visual interactivity
        setDesigns(prev => prev.map(d => d.id === id ? { ...d, status: targetStatus } : d));
      } else {
        // Update live database node
        const ref = doc(db, 'ai_custom_designs', id);
        await updateDoc(ref, {
          status: targetStatus,
          updatedAt: serverTimestamp()
        });
      }
    } catch (err) {
      alert(t.alertSaveErr + err.message);
    } finally {
      setProcessingId(null);
    }
  };

  // --- Robust Format Helpers (With Null-Safety Checks) ---
  const formatTimestamp = (ts) => {
    if (!ts) return locale === 'vi' ? 'Vừa xong' : 'Just now';
    const loc = locale === 'vi' ? 'vi-VN' : 'en-US';
    if (ts.toDate) {
      return ts.toDate().toLocaleString(loc, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
    }
    if (ts instanceof Date) {
      return ts.toLocaleString(loc, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
    }
    return String(ts);
  };

  const getStatusBadge = (status) => {
    const config = {
      'Created': { bg: 'rgba(59, 130, 246, 0.12)', color: '#3B82F6', label: t.badgeCreated, Icon: Clock },
      'Manufacturability Review': { bg: 'rgba(255, 152, 0, 0.12)', color: '#FF9800', label: t.badgeReview, Icon: Hammer },
      'Feasibility Approved': { bg: 'rgba(76, 175, 80, 0.12)', color: '#4CAF50', label: t.badgeApproved, Icon: CheckCircle },
      'Rejected': { bg: 'rgba(244, 67, 54, 0.12)', color: '#F44336', label: t.badgeRejected, Icon: AlertCircle }
    };

    const c = config[status] || config['Created'];
    return (
      <span className="badge" style={{ 
        background: c.bg, 
        color: c.color, 
        border: `1px solid ${c.color}25`,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        fontWeight: '600'
      }}>
        <c.Icon size={12} />
        {c.label}
      </span>
    );
  };

  // --- Filtering & Searching logic (Null-Safe) ---
  const filteredDesigns = designs.filter(d => {
    const safePrompt = (d.prompt || '').toLowerCase();
    const safeMaterial = (d.material || '').toLowerCase();
    const safeEmail = (d.customerEmail || '').toLowerCase();
    const matchesSearch = safePrompt.includes(searchQuery.toLowerCase()) || 
                          safeMaterial.includes(searchQuery.toLowerCase()) ||
                          safeEmail.includes(searchQuery.toLowerCase());
    
    const matchesStatus = statusFilter === 'all' || d.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  return (
    <div>
      <div className="header-bar">
        <div>
          <h1 className="page-title" style={{ fontSize: '2.25rem', color: 'var(--text-primary)' }}>{t.title}</h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '6px' }}>{t.subtitle}</p>
        </div>
      </div>

      {/* Filter and Search Controller Bar */}
      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '20px', marginBottom: '28px' }}>
        <div className="glass-panel" style={{ padding: '12px 20px', display: 'flex', alignItems: 'center', gap: '12px' }}>
          <Search size={18} color="var(--text-secondary)" />
          <input 
            type="text" 
            placeholder={t.searchPlaceholder}
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            style={{ 
              background: 'transparent', 
              border: 'none', 
              color: 'var(--text-primary)', 
              outline: 'none', 
              fontSize: '0.95rem',
              width: '100%' 
            }}
          />
        </div>

        <div className="glass-panel" style={{ padding: '10px 16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Sliders size={16} color="var(--gold-primary)" />
          <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: '600' }}>{t.statusLabel}</span>
          <select 
            value={statusFilter} 
            onChange={e => setStatusFilter(e.target.value)}
            style={{ 
              background: 'transparent', 
              border: 'none', 
              color: 'var(--text-primary)', 
              outline: 'none', 
              fontSize: '0.85rem',
              flex: 1,
              cursor: 'pointer'
            }}
          >
            <option value="all">{t.filterAll}</option>
            <option value="Created">{t.filterCreated}</option>
            <option value="Manufacturability Review">{t.filterReview}</option>
            <option value="Feasibility Approved">{t.filterApproved}</option>
            <option value="Rejected">{t.filterRejected}</option>
          </select>
        </div>
      </div>

      {loading ? (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '200px', color: 'var(--text-secondary)' }}>
          <Clock className="spin" style={{ marginRight: '8px' }} /> {t.loadingText}
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(360px, 1fr))', gap: '28px' }}>
          {filteredDesigns.length === 0 ? (
            <div className="glass-panel" style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '48px', color: 'var(--text-muted)' }}>
              <HelpCircle size={32} style={{ margin: '0 auto 12px', opacity: 0.6 }} />
              {t.noDesigns}
            </div>
          ) : (
            filteredDesigns.map(design => (
              <DesignCard 
                key={design.id} 
                design={design}
                processingId={processingId}
                updateDesignStatus={updateDesignStatus}
                formatTimestamp={formatTimestamp}
                getStatusBadge={getStatusBadge}
                t={t}
              />
            ))
          )}
        </div>
      )}
    </div>
  );
}

// --- High-Performance Optimized Sub-Component (Web Equivalent of Flutter's RepaintBoundary) ---
const DesignCard = React.memo(({ design, processingId, updateDesignStatus, formatTimestamp, getStatusBadge, t }) => {
  return (
    <div 
      className="glass-panel" 
      style={{ 
        display: 'flex', 
        flexDirection: 'column', 
        justifyContent: 'space-between',
        border: '1px solid rgba(212,175,55,0.12)',
        overflow: 'hidden',
        padding: 0,
        contentVisibility: 'auto', // Dynamic Paint Guard: Prevents paint operations for off-screen list elements
        containIntrinsicSize: '0 450px', // Allocates browser geometry reservation
        willChange: 'transform' // GPU Layer Compositing: Forces independent graphic redraw buffer (RepaintBoundary equivalent)
      }}
    >
      {/* AI Render Image Canvas */}
      <div style={{ position: 'relative', width: '100%', height: '240px', background: '#0D0D0E', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
        {design.imageUrl ? (
          <img 
            src={design.imageUrl} 
            alt="AI Jewelry Design" 
            style={{ width: '100%', height: '100%', objectFit: 'cover' }} 
            onError={(e) => {
              e.target.style.display = 'none';
              e.target.parentNode.style.display = 'flex';
              e.target.parentNode.style.alignItems = 'center';
              e.target.parentNode.style.justifyContent = 'center';
            }}
          />
        ) : (
          <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
            <Sparkles size={32} style={{ marginBottom: '8px', opacity: 0.4 }} />
            <span style={{ fontSize: '0.8rem' }}>AI Render Pending...</span>
          </div>
        )}

        {/* Status Overlay */}
        <div style={{ position: 'absolute', top: '16px', left: '16px' }}>
          {getStatusBadge(design.status)}
        </div>
      </div>

      {/* Card Context */}
      <div style={{ padding: '24px', flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
        <div>
          {/* Customer Meta */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-secondary)', fontSize: '0.8rem' }}>
              <User size={14} />
              <span style={{ fontWeight: '500' }}>{design.customerEmail}</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-muted)', fontSize: '0.75rem' }}>
              <Clock size={12} />
              <span>{formatTimestamp(design.createdAt)}</span>
            </div>
          </div>

          {/* Generative Prompt Details */}
          <div style={{ background: 'rgba(0,0,0,0.2)', padding: '12px 14px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.03)', marginBottom: '16px' }}>
            <p style={{ fontSize: '0.75rem', color: 'var(--gold-primary)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
              <Sparkles size={10} /> {t.clientPrompt}
            </p>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-primary)', lineHeight: '1.4', fontStyle: 'italic' }}>
              "{design.prompt}"
            </p>
          </div>

          {/* Material Specs */}
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '20px' }}>
            <Gem size={15} color="var(--gold-primary)" style={{ marginTop: '2px', flexShrink: 0 }} />
            <div>
              <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: '600' }}>{t.selectedComposition}</p>
              <p style={{ fontSize: '0.825rem', color: 'var(--text-primary)', marginTop: '2px', fontWeight: '500' }}>{design.material}</p>
            </div>
          </div>
        </div>

        {/* Operational Switch Actions */}
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '16px', display: 'flex', gap: '8px' }}>
          {design.status === 'Created' && (
            <button
              disabled={processingId === design.id}
              onClick={() => updateDesignStatus(design.id, 'Manufacturability Review')}
              className="btn btn-primary"
              style={{ flex: 1, padding: '10px', fontSize: '0.85rem', justifyContent: 'center' }}
            >
              <Hammer size={14} style={{ marginRight: '6px' }} />
              <span>{t.btnReview}</span>
            </button>
          )}

          {design.status === 'Manufacturability Review' && (
            <>
              <button
                disabled={processingId === design.id}
                onClick={() => updateDesignStatus(design.id, 'Feasibility Approved')}
                className="btn"
                style={{ flex: 1, padding: '10px', fontSize: '0.85rem', background: 'rgba(76,175,80,0.12)', color: '#4CAF50', border: '1px solid rgba(76,175,80,0.3)', justifyContent: 'center' }}
              >
                <CheckCircle size={14} style={{ marginRight: '4px' }} /> {t.btnApprove}
              </button>
              <button
                disabled={processingId === design.id}
                onClick={() => updateDesignStatus(design.id, 'Rejected')}
                className="btn"
                style={{ padding: '10px 14px', fontSize: '0.85rem', background: 'rgba(244,67,54,0.12)', color: '#F44336', border: '1px solid rgba(244,67,54,0.3)', justifyContent: 'center' }}
              >
                {t.btnReject}
              </button>
            </>
          )}

          {(design.status === 'Feasibility Approved' || design.status === 'Rejected') && (
            <button
              onClick={() => updateDesignStatus(design.id, 'Created')}
              className="btn btn-secondary"
              style={{ flex: 1, padding: '10px', fontSize: '0.85rem', justifyContent: 'center' }}
            >
              {t.btnReset}
            </button>
          )}
        </div>
      </div>
    </div>
  );
});

// Set display name for react devtools
DesignCard.displayName = 'DesignCard';
